//! Rust half of the in-app NIP-55 plugin.
//!
//! Thin proxy: each command forwards to the Kotlin `Nip55Plugin` via
//! `run_mobile_plugin` and returns its JSON verbatim. All protocol logic
//! (ContentResolver-vs-intent, npub→hex) lives Kotlin-side; all crypto
//! validation lives engine-side (`verify_signed_event`). The WebView calls
//! these as `plugin:nip55|<command>` through `window.__TAURI__.core.invoke`
//! (permissions: the `nip55:default` set granted in capabilities/mobile.json,
//! generated by the InlinedPlugin block in build.rs).
//!
//! On non-Android targets every command errors: NIP-55 is an Android
//! protocol, and the desktop host build exists only for host-logic iteration.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use tauri::{
    plugin::{Builder, TauriPlugin},
    Runtime,
};

#[cfg(target_os = "android")]
struct Nip55<R: Runtime>(tauri::plugin::PluginHandle<R>);

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct GetPublicKeyArgs {
    package_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    permissions: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct SignEventArgs {
    package_name: String,
    event_json: String,
    id: String,
    current_user: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct CipherArgs {
    package_name: String,
    content: String,
    id: String,
    current_user: String,
    pubkey: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct EmptyArgs {}

#[cfg(target_os = "android")]
fn forward<R: Runtime, T: serde::Serialize>(
    app: &tauri::AppHandle<R>,
    command: &str,
    args: T,
) -> Result<Value, String> {
    use tauri::Manager;
    let handle = app.state::<Nip55<R>>();
    handle
        .0
        .run_mobile_plugin::<Value>(command, args)
        .map_err(|e| e.to_string())
}

#[cfg(not(target_os = "android"))]
fn unsupported() -> Result<Value, String> {
    Err("NIP-55 signer apps are Android-only".into())
}

#[tauri::command]
async fn get_installed_signer_apps<R: Runtime>(
    app: tauri::AppHandle<R>,
) -> Result<Value, String> {
    #[cfg(target_os = "android")]
    return forward(&app, "getInstalledSignerApps", EmptyArgs {});
    #[cfg(not(target_os = "android"))]
    {
        let _ = app;
        unsupported()
    }
}

#[tauri::command]
async fn get_public_key<R: Runtime>(
    app: tauri::AppHandle<R>,
    package_name: String,
    permissions: Option<String>,
) -> Result<Value, String> {
    #[cfg(target_os = "android")]
    return forward(
        &app,
        "getPublicKey",
        GetPublicKeyArgs {
            package_name,
            permissions,
        },
    );
    #[cfg(not(target_os = "android"))]
    {
        let _ = (app, package_name, permissions);
        unsupported()
    }
}

#[tauri::command]
async fn sign_event<R: Runtime>(
    app: tauri::AppHandle<R>,
    package_name: String,
    event_json: String,
    id: String,
    current_user: String,
) -> Result<Value, String> {
    #[cfg(target_os = "android")]
    return forward(
        &app,
        "signEvent",
        SignEventArgs {
            package_name,
            event_json,
            id,
            current_user,
        },
    );
    #[cfg(not(target_os = "android"))]
    {
        let _ = (app, package_name, event_json, id, current_user);
        unsupported()
    }
}

macro_rules! cipher_command {
    ($name:ident, $kotlin:literal) => {
        #[tauri::command]
        async fn $name<R: Runtime>(
            app: tauri::AppHandle<R>,
            package_name: String,
            content: String,
            id: String,
            current_user: String,
            pubkey: String,
        ) -> Result<Value, String> {
            #[cfg(target_os = "android")]
            return forward(
                &app,
                $kotlin,
                CipherArgs {
                    package_name,
                    content,
                    id,
                    current_user,
                    pubkey,
                },
            );
            #[cfg(not(target_os = "android"))]
            {
                let _ = (app, package_name, content, id, current_user, pubkey);
                unsupported()
            }
        }
    };
}

cipher_command!(nip04_encrypt, "nip04Encrypt");
cipher_command!(nip04_decrypt, "nip04Decrypt");
cipher_command!(nip44_encrypt, "nip44Encrypt");
cipher_command!(nip44_decrypt, "nip44Decrypt");

pub fn init<R: Runtime>() -> TauriPlugin<R> {
    Builder::new("nip55")
        .invoke_handler(tauri::generate_handler![
            get_installed_signer_apps,
            get_public_key,
            sign_event,
            nip04_encrypt,
            nip04_decrypt,
            nip44_encrypt,
            nip44_decrypt
        ])
        .setup(|_app, _api| {
            #[cfg(target_os = "android")]
            {
                use tauri::Manager;
                let handle =
                    _api.register_android_plugin("io.github.limina1.tendrl", "Nip55Plugin")?;
                _app.manage(Nip55(handle));
            }
            Ok(())
        })
        .build()
}
